//------------------------------------------------------------------------------
// <auto-generated>
//     Phase 21 / Improvement #18 — .resx-локализация.
//
//     Этот файл написан вручную (без ResXFileCodeGenerator), чтобы
//     генерация ресурсов не зависела от Visual Studio: SDK-style csproj
//     эмбедит Resources\Strings.resx и собирает satellite-сборки из
//     Strings.<culture>.resx автоматически, а здесь — типизированные
//     обёртки над <see cref="System.Resources.ResourceManager"/>.
//
//     Чтобы добавить новый ключ:
//       1) Добавьте data-узел в Resources/Strings.resx (и параллельных
//          культурах, например Strings.en-US.resx).
//       2) Добавьте здесь публичный static property с тем же именем,
//          возвращающий ResourceManager.GetString("...", Culture).
//
//     Использование:
//
//       // в коде
//       var title = AhuErp.UI.Resources.Strings.Login_WindowTitle;
//
//       // в XAML
//       xmlns:res="clr-namespace:AhuErp.UI.Resources"
//       <Window Title="{x:Static res:Strings.Login_WindowTitle}" />
//
//     Чтобы переключить язык во время выполнения, выставьте
//     Thread.CurrentThread.CurrentUICulture и/или
//     <see cref="Strings.Culture"/> в начале App.OnStartup.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhuErp.UI.Resources
{
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    /// Строго типизированный доступ к строкам в Resources/Strings.resx
    /// (нейтральная культура — русский). Альтернативные культуры
    /// (например, en-US) подцепляются автоматически через сателлитные
    /// сборки, собираемые из Strings.&lt;culture&gt;.resx.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AhuErp.UI", "21.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public static class Strings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        /// <summary>
        /// Возвращает кэшированный <see cref="ResourceManager"/>,
        /// привязанный к Resources/Strings.resx в текущей сборке.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceMan is null)
                {
                    _resourceMan = new ResourceManager(
                        "AhuErp.UI.Resources.Strings",
                        typeof(Strings).Assembly);
                }
                return _resourceMan;
            }
        }

        /// <summary>
        /// Перекрывает культуру, в которой по умолчанию читаются строки.
        /// Если <c>null</c> — берётся <see cref="CultureInfo.CurrentUICulture"/>.
        /// </summary>
        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        // ---- Common ---------------------------------------------------------
        public static string Common_Save    => ResourceManager.GetString(nameof(Common_Save),    _resourceCulture);
        public static string Common_Cancel  => ResourceManager.GetString(nameof(Common_Cancel),  _resourceCulture);
        public static string Common_Delete  => ResourceManager.GetString(nameof(Common_Delete),  _resourceCulture);
        public static string Common_Add     => ResourceManager.GetString(nameof(Common_Add),     _resourceCulture);
        public static string Common_Edit    => ResourceManager.GetString(nameof(Common_Edit),    _resourceCulture);
        public static string Common_Refresh => ResourceManager.GetString(nameof(Common_Refresh), _resourceCulture);
        public static string Common_Close   => ResourceManager.GetString(nameof(Common_Close),   _resourceCulture);
        public static string Common_Yes     => ResourceManager.GetString(nameof(Common_Yes),     _resourceCulture);
        public static string Common_No      => ResourceManager.GetString(nameof(Common_No),      _resourceCulture);

        // ---- Login window ---------------------------------------------------
        public static string Login_WindowTitle    => ResourceManager.GetString(nameof(Login_WindowTitle),    _resourceCulture);
        public static string Login_OrgShort       => ResourceManager.GetString(nameof(Login_OrgShort),       _resourceCulture);
        public static string Login_OrgSubtitle    => ResourceManager.GetString(nameof(Login_OrgSubtitle),    _resourceCulture);
        public static string Login_FullNameLabel  => ResourceManager.GetString(nameof(Login_FullNameLabel),  _resourceCulture);
        public static string Login_PasswordLabel  => ResourceManager.GetString(nameof(Login_PasswordLabel),  _resourceCulture);
        public static string Login_SignInButton   => ResourceManager.GetString(nameof(Login_SignInButton),   _resourceCulture);

        // ---- Main window / navigation --------------------------------------
        public static string Main_WindowTitle => ResourceManager.GetString(nameof(Main_WindowTitle), _resourceCulture);
        public static string Nav_Dashboard    => ResourceManager.GetString(nameof(Nav_Dashboard),    _resourceCulture);
        public static string Nav_MyDesktop    => ResourceManager.GetString(nameof(Nav_MyDesktop),    _resourceCulture);
        public static string Nav_Journal      => ResourceManager.GetString(nameof(Nav_Journal),      _resourceCulture);
        public static string Nav_MyTasks      => ResourceManager.GetString(nameof(Nav_MyTasks),      _resourceCulture);
        public static string Nav_Warehouse    => ResourceManager.GetString(nameof(Nav_Warehouse),    _resourceCulture);
        public static string Nav_Fleet        => ResourceManager.GetString(nameof(Nav_Fleet),        _resourceCulture);
        public static string Nav_Archive      => ResourceManager.GetString(nameof(Nav_Archive),      _resourceCulture);
        public static string Nav_ItService    => ResourceManager.GetString(nameof(Nav_ItService),    _resourceCulture);
        public static string Nav_AuditJournal => ResourceManager.GetString(nameof(Nav_AuditJournal), _resourceCulture);
        public static string Nav_Settings     => ResourceManager.GetString(nameof(Nav_Settings),     _resourceCulture);
        public static string Nav_Logout       => ResourceManager.GetString(nameof(Nav_Logout),       _resourceCulture);

        // ---- Errors ---------------------------------------------------------
        public static string Error_FatalTitle               => ResourceManager.GetString(nameof(Error_FatalTitle),               _resourceCulture);
        public static string Error_LoginInvalidCredentials  => ResourceManager.GetString(nameof(Error_LoginInvalidCredentials),  _resourceCulture);
        public static string Error_AccountLocked            => ResourceManager.GetString(nameof(Error_AccountLocked),            _resourceCulture);
        public static string Error_AccountInactive          => ResourceManager.GetString(nameof(Error_AccountInactive),          _resourceCulture);
        public static string Error_PasswordExpired          => ResourceManager.GetString(nameof(Error_PasswordExpired),          _resourceCulture);
    }
}
